changelog:
  exclude:
    labels:
      - ignore-for-release
      - chore
      - tests
    authors:
      - octocat
  categories:
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Performance
      labels:
        - performance
    - title: Security
      labels:
        - security
  