name: Run Docker container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Run Docker container
        run: make run