name: Run Docker container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t semantic-release .

      - name: Check GH_TOKEN
        run: |
          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          docker run \
            --user $USER_ID:$GROUP_ID \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v ${{ github.workspace }}:/app \
            -w /app \
            semantic-release \
            /bin/sh -c "echo GITHUB_TOKEN is set: ${GITHUB_TOKEN:+yes}"

      - name: Run semantic-release
        run: |
          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          docker run \
            --user $USER_ID:$GROUP_ID \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v ${{ github.workspace }}:/app \
            -w /app \
            semantic-release \
            /bin/sh -c "git checkout master && GITHUB_TOKEN=${GITHUB_TOKEN} semantic-release"
